"""
Django settings for tourism_project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent
# Load environment variables from project-level .env file reliably.
load_dotenv(dotenv_path=BASE_DIR / ".env", override=True)


def _env_bool(name, default=False):
    raw = str(os.getenv(name, str(default))).strip().lower()
    return raw in {"1", "true", "yes", "on"}


def _env_int(name, default):
    try:
        return int(str(os.getenv(name, str(default))).strip())
    except (TypeError, ValueError):
        return default


def _env_list(name, default=None):
    raw = str(os.getenv(name, "")).strip()
    if raw:
        return [item.strip() for item in raw.split(",") if item.strip()]
    return list(default or [])


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "").strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-set-SECRET_KEY-in-env"
    else:
        raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG=False.")

ALLOWED_HOSTS = _env_list(
    "ALLOWED_HOSTS",
    default=[
        "127.0.0.1",
        "localhost",
        "unetymological-earnestine-aneurysmally.ngrok-free.dev",
    ],
)



# Application definition
CRISPY_TEMPLATE_PACK = 'bootstrap4'  # or 'bootstrap5' depending on your choice
MEDIA_URL = "/media/"  # URL to serve media files
MEDIA_ROOT = BASE_DIR / "media"  # Path where media files are stored

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'mathfilters',
    'crispy_forms',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'tour_app',
    'admin_app',
    'guest_app',
    'accom_app',
    'request_app',
    'ai_chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

ROOT_URLCONF = 'tourism_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tourism_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

_cloud_db_engine = os.getenv("DB_ENGINE", "django.db.backends.mysql")
_cloud_db_name = os.getenv("DB_NAME", "")
_cloud_db_user = os.getenv("DB_USER", "")
_cloud_db_password = os.getenv("DB_PASSWORD", "")
_cloud_db_host = os.getenv("DB_HOST", "")
_cloud_db_port = os.getenv("DB_PORT", "3306")

_has_cloud_mysql_env = all([_cloud_db_name, _cloud_db_user, _cloud_db_password, _cloud_db_host])

if _has_cloud_mysql_env:
    DATABASES = {
        "default": {
            "ENGINE": _cloud_db_engine,
            "NAME": _cloud_db_name,
            "USER": _cloud_db_user,
            "PASSWORD": _cloud_db_password,
            "HOST": _cloud_db_host,
            "PORT": _cloud_db_port,
            "CONN_MAX_AGE": _env_int("DB_CONN_MAX_AGE", 60),
            "OPTIONS": {
                "charset": "utf8mb4",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": os.getenv("LOCAL_DB_ENGINE", "django.db.backends.mysql"),
            "NAME": os.getenv("LOCAL_DB_NAME", "project_db"),
            "USER": os.getenv("LOCAL_DB_USER", "root"),
            "PASSWORD": os.getenv("LOCAL_DB_PASSWORD", os.getenv("MYSQL_PASSWORD", "")),
            "HOST": os.getenv("LOCAL_DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("LOCAL_DB_PORT", "3307"),
            "OPTIONS": {
                "charset": "utf8mb4",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Add supported languages
LANGUAGES = [
    ('en', 'English'),
    ('tl', 'Tagalog'),
    ('ceb', 'Cebuano'),
    ('es', 'Spanish'),
]

# This is the key Django will use in the session
LANGUAGE_SESSION_KEY = 'django_language'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

SESSION_COOKIE_AGE = 1800  # Session expires after 30 minutes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Session expires when the browser is closed
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", not DEBUG)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Store session in DB
SESSION_COOKIE_NAME = 'sessionid'  # Default session cookie name
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to the session cookie
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
SESSION_SAVE_EVERY_REQUEST = True  # Save the session on every request
# settings.py

# Ensure @login_required redirects to an existing route (guest-facing pages use guest login).
LOGIN_URL = '/guest_app/login/'

AUTHENTICATION_BACKENDS = [
    'guest_app.backends.GuestAuthenticationBackend',  # Add your custom backend here
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',  # Keep the default backend (optional)
]

# Configure where uploaded files are stored
# settings.py

# Email configuration settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = _env_int("EMAIL_PORT", 587)
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    f'IBAYAW Tours <{EMAIL_HOST_USER}>' if EMAIL_HOST_USER else "IBAYAW Tours <noreply@localhost>",
)

# CSRF settings to fix form submission issues
CSRF_TRUSTED_ORIGINS = _env_list(
    "CSRF_TRUSTED_ORIGINS",
    default=["http://localhost:8000", "http://127.0.0.1:8000"],
)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
CSRF_USE_SESSIONS = True  # Store CSRF token in the session instead of cookie

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SECURE_HSTS_SECONDS = _env_int("SECURE_HSTS_SECONDS", 31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", not DEBUG)
SECURE_REFERRER_POLICY = os.getenv("SECURE_REFERRER_POLICY", "same-origin")
SECURE_CONTENT_TYPE_NOSNIFF = _env_bool("SECURE_CONTENT_TYPE_NOSNIFF", True)
X_FRAME_OPTIONS = os.getenv("X_FRAME_OPTIONS", "DENY")

# If you're using Gmail, you may need to create an App Password:
# 1. Go to your Google Account > Security
# 2. Enable 2-Step Verification if not already enabled
# 3. Go to App passwords
# 4. Select "Mail" and "Other" (Custom name: "Django")
# 5. Use the generated 16-character password as EMAIL_HOST_PASSWORD

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'guest_app.Guest'  # Replace 'guest_app' with your app name

SITE_ID = _env_int("SITE_ID", 1)
LOGIN_REDIRECT_URL = "/guest_app/main-page/"
ACCOUNT_LOGOUT_ON_GET = _env_bool("ACCOUNT_LOGOUT_ON_GET", False)
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_ADAPTER = "guest_app.social_adapter.GuestSocialAccountAdapter"
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_OAUTH_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
    "facebook": {
        "APP": {
            "client_id": os.getenv("FACEBOOK_OAUTH_APP_ID", ""),
            "secret": os.getenv("FACEBOOK_OAUTH_APP_SECRET", ""),
            "key": "",
        },
        "METHOD": "oauth2",
        "SCOPE": ["email", "public_profile"],
        "FIELDS": ["id", "email", "name", "first_name", "last_name"],
        "VERIFIED_EMAIL": False,
    },
}

# External payment/billing page used by chatbot booking responses.
# Set in .env for production, e.g. TOURISM_OFFICE_BILLING_URL=https://billing.example.com/pay
TOURISM_OFFICE_BILLING_URL = os.environ.get('TOURISM_OFFICE_BILLING_URL', '')
# Treasurer Office billing handoff for tour package payments.
TOURISM_TREASURER_BILLING_URL = os.environ.get('TOURISM_TREASURER_BILLING_URL', TOURISM_OFFICE_BILLING_URL)

# Security keys
RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY', '')
RECAPTCHA_SITE_KEY = os.environ.get('RECAPTCHA_SITE_KEY', '')

