# Generated by Django 5.1.6 on 2025-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_admininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
