# Generated by Django 5.1.6 on 2025-03-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_admininfo_is_active_admininfo_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='is_active',
        ),
    ]
