# Generated by Django 5.1.6 on 2025-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_admininfo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
