# Generated by Django 5.1.6 on 2025-03-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_admininfo_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
    ]
