# Generated by Django 5.1.6 on 2025-03-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_dynamicentry_region_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('month_to_be_submitted', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='DynamicEntry',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='admin_app.region'),
        ),
        migrations.AddField(
            model_name='establishmentform',
            name='countries',
            field=models.ManyToManyField(related_name='establishment_forms', to='admin_app.country'),
        ),
        migrations.AddField(
            model_name='establishmentform',
            name='entries',
            field=models.ManyToManyField(related_name='establishment_forms', to='admin_app.entry'),
        ),
        migrations.AddField(
            model_name='establishmentform',
            name='regions',
            field=models.ManyToManyField(related_name='establishment_forms', to='admin_app.region'),
        ),
    ]
