# Generated by Django 5.1.6 on 2025-03-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_entry_establishmentform_delete_dynamicentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishmentform',
            name='date',
        ),
        migrations.RemoveField(
            model_name='establishmentform',
            name='month',
        ),
        migrations.RemoveField(
            model_name='establishmentform',
            name='month_to_be_submitted',
        ),
    ]
