# Generated by Django 5.1.6 on 2025-03-17 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_remove_establishmentform_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.region'),
        ),
    ]
