# Generated by Django 5.1.6 on 2025-03-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_alter_entry_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='region',
        ),
    ]
