# Generated by Django 5.1.6 on 2025-03-22 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0011_accommodation'),
        ('admin_app', '0013_entry_description_entry_is_hotel_alter_entry_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_submitted', models.CharField(max_length=20)),
                ('entry_ans', models.TextField(blank=True, null=True)),
                ('hotel', models.CharField(default='0', max_length=1)),
                ('accom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accom_app.accommodation')),
            ],
        ),
    ]
