# Generated by Django 5.1.7 on 2025-04-05 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_alter_employee_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_profiles/'),
        ),
        migrations.CreateModel(
            name='AccommodationCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodation_certifications/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='admin_app.accomodation')),
            ],
        ),
    ]
