# Generated by Django 5.1.6 on 2025-04-04 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_alter_employee_last_login'),
        ('tour_app', '0028_touraddtranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_assignments', to='admin_app.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='tour_app.tour_schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_app.tour_event')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='admin_app.tourassignment')),
            ],
        ),
    ]
