# Generated by Django 5.1.6 on 2025-04-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_guest_room_roomassignment'),
    ]

    operations = [
        # Add status column (SQLite compatible)
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=15),
        ),
        
        # Now add the unique constraint
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('accommodation', 'room_name')},
        ),
    ]
