# Generated by Django 5.1.7 on 2025-04-05 13:35

from django.db import migrations

def deduplicate_room_names(apps, schema_editor):
    """
    Find duplicate room names for the same accommodation and rename them to make them unique.
    """
    Room = apps.get_model('admin_app', 'Room')
    
    # Get all accommodations
    accommodations = set(Room.objects.values_list('accommodation_id', flat=True))
    
    for accom_id in accommodations:
        # Get all rooms for this accommodation
        rooms = Room.objects.filter(accommodation_id=accom_id)
        
        # Find duplicate room names
        room_names = {}
        for room in rooms:
            if room.room_name in room_names:
                room_names[room.room_name].append(room)
            else:
                room_names[room.room_name] = [room]
        
        # Rename duplicates
        for name, room_list in room_names.items():
            if len(room_list) > 1:
                # Keep the first one as is, rename others
                for i, room in enumerate(room_list[1:], 1):
                    room.room_name = f"{name} (Copy {i})"
                    room.save()


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_room_status_alter_room_unique_together'),
    ]

    operations = [
        migrations.RunPython(deduplicate_room_names),
    ]
