# Generated by Django 6.0.1 on 2026-02-03 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_tourassignment_itinerarychecklistitem'),
        ('admin_app', '0021_room_status_alter_roomassignment_guest'),
    ]

    operations = [
    ]
