# Generated by Django 6.0.1 on 2026-02-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0019_alter_other_estab_intended_month_alter_room_accom_id_and_more'),
        ('admin_app', '0022_merge_20260203_0921'),
        ('tour_app', '0028_touraddtranslation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.AlterUniqueTogether(
            name='tourassignment',
            unique_together={('employee', 'schedule')},
        ),
        migrations.DeleteModel(
            name='ItineraryChecklistItem',
        ),
    ]
