# Generated by Codex on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_delete_guest_alter_tourassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
