# Generated by Django 6.0.1 on 2026-02-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_delete_guest_alter_tourassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourassignment',
            name='assignment_id',
        ),
        migrations.AddField(
            model_name='tourassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
