# Generated by Django 5.2.4 on 2026-04-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0032_rename_admin_app_in_recipie_922495_idx_admin_app_i_recipie_a8067b_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inappnotification',
            new_name='admin_app_i_recipie_a8067b_idx',
            old_name='admin_app_in_recipie_922495_idx',
        ),
        migrations.RenameIndex(
            model_name='inappnotification',
            new_name='admin_app_i_recipie_cfaca1_idx',
            old_name='admin_app_in_recipie_70f545_idx',
        ),
    ]
