# Generated by Django 5.2.4 on 2026-04-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0033_rename_admin_app_in_recipie_922495_idx_admin_app_i_recipie_a8067b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreportroomusage',
            name='room_identifiers_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monthlyreportroomusage',
            name='total_rooms_snapshot',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='room_identifiers',
            field=models.TextField(blank=True, default='', help_text='Optional room IDs/numbers for this room type (e.g., 101,102 or SS-001 to SS-031).'),
        ),
        migrations.AddField(
            model_name='room',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1, help_text='Total number of rooms available under this room type.'),
        ),
    ]
