# Generated by Django 5.2.4 on 2026-04-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_monthlyreportroomusage_room_identifiers_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyreportroomusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlyreportroomusage',
            name='selected_room_identifier',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
