# Generated by Django 5.1.6 on 2025-03-15 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0007_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherEstab',
            fields=[
                ('estab_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('residences', models.IntegerField(blank=True, null=True)),
                ('total_foreign_travelers', models.IntegerField(blank=True, null=True)),
                ('overseas', models.IntegerField(blank=True, null=True)),
                ('domestic', models.IntegerField(blank=True, null=True)),
                ('accom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.accomodation')),
            ],
        ),
    ]
