# Generated by Django 5.1.6 on 2025-03-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0001_initial'),
        ('admin_app', '0007_employee_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherEstab',
            new_name='Other_Estab',
        ),
    ]
