# Generated by Django 5.1.6 on 2025-03-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0002_rename_otherestab_other_estab'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_estab',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='other_estab',
            name='intended_month',
            field=models.CharField(default='March', max_length=20),
        ),
    ]
