# Generated by Django 5.1.6 on 2025-03-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0003_other_estab_date_other_estab_intended_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_estab',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
