# Generated by Django 5.1.6 on 2025-03-19 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0004_other_estab_dynamic_fields'),
        ('admin_app', '0012_remove_entry_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_submit', models.DateField()),
                ('month_actual', models.DateField()),
                ('guest_num', models.IntegerField()),
                ('total_num', models.IntegerField()),
                ('accom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.accomodation')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.country')),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.entry')),
            ],
        ),
    ]
