# Generated by Django 5.1.6 on 2025-03-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0005_summary'),
        ('admin_app', '0012_remove_entry_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='month_submit',
            new_name='month_submitted',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='total_num',
        ),
        migrations.AddField(
            model_name='summary',
            name='entry_ans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='overall_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='region_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.region'),
        ),
        migrations.AddField(
            model_name='summary',
            name='sub_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.country'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='entry_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.entry'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='guest_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
