# Generated by Django 5.1.6 on 2025-03-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0006_rename_month_submit_summary_month_submitted_and_more'),
        ('admin_app', '0012_remove_entry_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('accom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.accomodation')),
            ],
        ),
    ]
