# Generated by Django 5.1.6 on 2025-03-21 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0007_hotelrooms'),
        ('admin_app', '0012_remove_entry_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsGuestAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.DateField()),
                ('checked_out', models.DateField()),
                ('no_of_nights', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('accom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.accomodation')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accom_app.hotelrooms')),
            ],
        ),
    ]
