# Generated by Django 5.1.6 on 2025-03-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0008_roomsguestadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrooms',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
