# Generated by Django 5.1.6 on 2025-03-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0009_hotelrooms_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='hotel',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
