# Generated by Django 5.1.6 on 2025-03-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0011_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsguestadd',
            name='num_guests',
            field=models.IntegerField(default=1),
        ),
    ]
