# Generated by Django 5.1.6 on 2025-04-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0012_roomsguestadd_num_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_estab',
            name='intended_month',
            field=models.CharField(default='April', max_length=20),
        ),
    ]
