# Generated by Django 5.1.6 on 2025-04-05 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0013_alter_other_estab_intended_month'),
        ('admin_app', '0017_tourassignment_itinerarychecklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='mies_table',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('company', models.CharField(max_length=255)),
                ('representative', models.CharField(max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grandtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_name', models.CharField(max_length=255)),
                ('accom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.accomodation')),
            ],
        ),
    ]
