# Generated by Django 5.1.7 on 2025-04-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0013_alter_other_estab_intended_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrooms',
            name='person_limit',
            field=models.IntegerField(default=2),
        ),
    ]
