# Generated by Django 5.1.6 on 2025-04-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0014_mies_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='mies_table',
            name='meeting_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
