# Generated by Django 5.1.7 on 2025-04-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0014_hotelrooms_person_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrooms',
            name='person_limit',
            field=models.IntegerField(default=0),
        ),
    ]
