# Generated by Django 5.1.6 on 2025-04-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0015_mies_table_meeting_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mies_table',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mies_table',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
