# Generated by Django 5.1.7 on 2025-04-05 13:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0015_alter_hotelrooms_person_limit'),
        ('admin_app', '0018_guest_room_roomassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(blank=True, max_length=100, null=True)),
                ('person_limit', models.IntegerField(default=0)),
                ('current_availability', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=15)),
                ('last_check_in', models.DateTimeField(blank=True, null=True)),
                ('last_check_out', models.DateTimeField(blank=True, null=True)),
                ('total_occupied_time', models.DurationField(default=datetime.timedelta(0))),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('accom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.accomodation')),
            ],
        ),
        migrations.AlterField(
            model_name='roomsguestadd',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accom_app.room'),
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('checked_in', models.DateTimeField(blank=True, null=True)),
                ('checked_out', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accom_room_assignments', to='admin_app.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accom_app.room')),
            ],
        ),
        migrations.DeleteModel(
            name='HotelRooms',
        ),
        migrations.CreateModel(
            name='HotelRooms',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accom_app.room',),
        ),
    ]
