# Generated by Django 5.1.6 on 2025-04-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0016_alter_mies_table_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mies_table',
            name='grandtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mies_table',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mies_table',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
