# Generated by Django 6.0.1 on 2026-02-03 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0016_update_room_model'),
        ('accom_app', '0017_alter_mies_table_grandtotal_and_more'),
    ]

    operations = [
    ]
