# Generated by Django 6.0.1 on 2026-02-03 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accom_app', '0018_merge_20260203_0921'),
        ('admin_app', '0022_merge_20260203_0921'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_estab',
            name='intended_month',
            field=models.CharField(default='February', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='accom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accom_rooms', to='admin_app.accomodation'),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accom_room_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
