# Generated by Django 5.1.6 on 2025-03-03 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0001_initial'),
        ('tour_app', '0019_remove_tour_event_tour_id_alter_tour_event_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bookings', to=settings.AUTH_USER_MODEL)),
                ('sched_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_schedules', to='tour_app.tour_schedule')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_tours', to='tour_app.tour_add')),
            ],
        ),
    ]
