# Generated by Django 5.1.6 on 2025-03-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0002_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
