# Generated by Django 5.1.6 on 2025-03-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0003_guest_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_id',
            field=models.CharField(blank=True, max_length=5, primary_key=True, serialize=False),
        ),
    ]
