# Generated by Django 5.1.6 on 2025-03-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0004_alter_guest_guest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
