# Generated by Django 5.1.6 on 2025-03-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0005_alter_guest_guest_id'),
        ('tour_app', '0020_admission_rates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pending',
            unique_together={('guest_id', 'sched_id', 'tour_id')},
        ),
    ]
