# Generated by Django 5.1.6 on 2025-03-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0006_alter_pending_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pending',
            unique_together=set(),
        ),
    ]
