# Generated by Django 5.1.6 on 2025-03-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0007_alter_pending_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='total_guests',
            field=models.IntegerField(default=1),
        ),
    ]
