# Generated by Django 5.1.6 on 2025-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0008_pending_total_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='num_adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pending',
            name='num_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pending',
            name='your_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='pending',
            name='your_name',
            field=models.CharField(default='Unknown Name', max_length=255),
        ),
        migrations.AddField(
            model_name='pending',
            name='your_phone',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
    ]
