# Generated by Django 5.1.6 on 2025-03-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0009_pending_num_adults_pending_num_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
