# Generated by Django 5.1.6 on 2025-03-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0012_mapbookmark'),
    ]

    operations = [
    ]
