# Generated by Django 5.1.6 on 2025-03-28 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0014_add_bookmark_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bookmark_images/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='guest_app.mapbookmark')),
            ],
        ),
    ]
