# Generated by Django 5.1.6 on 2025-03-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0015_bookmarkimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapbookmark',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='bookmark_primary_images/'),
        ),
    ]
