# Generated by Django 5.1.6 on 2025-04-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0016_mapbookmark_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkimage',
            name='description_ceb',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Cebuano)'),
        ),
        migrations.AddField(
            model_name='bookmarkimage',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='bookmarkimage',
            name='description_tl',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Tagalog)'),
        ),
        migrations.AddField(
            model_name='bookmarkimage',
            name='title_ceb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (Cebuano)'),
        ),
        migrations.AddField(
            model_name='bookmarkimage',
            name='title_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='bookmarkimage',
            name='title_tl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (Tagalog)'),
        ),
        migrations.AddField(
            model_name='mapbookmark',
            name='details_ceb',
            field=models.TextField(blank=True, null=True, verbose_name='Details (Cebuano)'),
        ),
        migrations.AddField(
            model_name='mapbookmark',
            name='details_es',
            field=models.TextField(blank=True, null=True, verbose_name='Details (Spanish)'),
        ),
        migrations.AddField(
            model_name='mapbookmark',
            name='details_tl',
            field=models.TextField(blank=True, null=True, verbose_name='Details (Tagalog)'),
        ),
        migrations.AddField(
            model_name='mapbookmark',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tl', 'Tagalog'), ('ceb', 'Cebuano'), ('es', 'Spanish')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='mapbookmark',
            name='name_ceb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Cebuano)'),
        ),
        migrations.AddField(
            model_name='mapbookmark',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='mapbookmark',
            name='name_tl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Tagalog)'),
        ),
    ]
