# Generated by Django 5.1.7 on 2025-04-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0017_bookmarkimage_description_ceb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pending',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
