# Generated by Django 5.1.7 on 2025-04-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0019_guest_age_label_guest_birthday_guest_disability_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
