# Generated by Django 5.1.7 on 2025-04-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0021_alter_guest_options_alter_guest_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
