# Generated by Django 5.1.7 on 2025-04-03 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0022_alter_guest_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companions', to=settings.AUTH_USER_MODEL),
        ),
    ]
