# Generated by Django 5.1.7 on 2025-04-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0024_companiongroup_guest_group'),
    ]

    operations = [
    ]
