# Generated by Django 5.1.7 on 2025-04-03 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0026_companionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionrequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companion_requests', to='guest_app.companiongroup'),
        ),
    ]
