# Generated by Django 6.0.1 on 2026-02-03 09:40

import guest_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0029_friendship'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='guest',
            managers=[
                ('objects', guest_app.models.GuestManager()),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(default='default_user', max_length=100, unique=True),
        ),
    ]
