# Generated by Django 6.0.1 on 2026-02-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_app', '0030_alter_guest_managers_alter_guest_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
