# Generated by Django 5.2.4 on 2026-04-29 14:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0035_alter_monthlyreportroomusage_unique_together_and_more'),
        ('guest_app', '0034_accommodationbookingcompanion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('moderation_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reviews', to='admin_app.accomodation')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_accommodation_reviews', to='admin_app.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'accommodation'], name='guest_app_a_status_96f663_idx')],
                'constraints': [models.UniqueConstraint(fields=('accommodation', 'guest'), name='unique_guest_accommodation_review')],
            },
        ),
    ]
