# Generated by Django 5.1.6 on 2025-02-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200)),
                ('tour_start_time', models.DateTimeField()),
                ('tour_end_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_images/')),
                ('tour_id', models.CharField(blank=True, max_length=7, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tour_add',
        ),
    ]
