# Generated by Django 5.1.6 on 2025-02-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0002_touradd_delete_tour_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touradd',
            name='id',
        ),
        migrations.AlterField(
            model_name='touradd',
            name='tour_id',
            field=models.CharField(blank=True, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
