# Generated by Django 5.1.6 on 2025-02-21 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0003_remove_touradd_id_alter_touradd_tour_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.TimeField()),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tour_app.touradd')),
            ],
        ),
    ]
