# Generated by Django 5.1.6 on 2025-02-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tour_app.touradd'),
        ),
    ]
