# Generated by Django 5.1.6 on 2025-02-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0005_alter_event_tour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourAdd',
            new_name='Tour_Add',
        ),
    ]
