# Generated by Django 5.1.6 on 2025-02-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0007_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payables', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_fees', to='tour_app.tour_add')),
            ],
        ),
    ]
