# Generated by Django 5.1.6 on 2025-02-26 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0008_admission_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_add',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tour_add',
            name='tour_end_time',
        ),
        migrations.RemoveField(
            model_name='tour_add',
            name='tour_start_time',
        ),
        migrations.CreateModel(
            name='Tour_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tour_app.tour_add')),
            ],
        ),
    ]
