# Generated by Django 5.1.6 on 2025-02-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0009_remove_tour_add_price_remove_tour_add_tour_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_add',
            name='tour_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
