# Generated by Django 5.1.6 on 2025-02-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0011_alter_tour_add_tour_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_add',
            name='tour_id',
            field=models.IntegerField(blank=True, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
