# Generated by Django 5.1.6 on 2025-02-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0013_alter_tour_add_tour_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_schedule',
            name='id',
        ),
        migrations.AddField(
            model_name='tour_schedule',
            name='sced_id',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
