# Generated by Django 5.1.6 on 2025-02-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0014_remove_tour_schedule_id_tour_schedule_sced_id'),
    ]

    operations = [
    ]
