# Generated by Django 5.1.6 on 2025-03-03 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0015_auto_20250227_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tour',
        ),
        migrations.RenameField(
            model_name='tour_schedule',
            old_name='sced_id',
            new_name='sched_id',
        ),
        migrations.RenameField(
            model_name='tour_schedule',
            old_name='tour',
            new_name='tour_id',
        ),
        migrations.CreateModel(
            name='Tour_Admission',
            fields=[
                ('Admis_id', models.AutoField(primary_key=True, serialize=False)),
                ('payables', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sched_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='tour_app.tour_schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Tour_Event',
            fields=[
                ('event_ID', models.AutoField(primary_key=True, serialize=False)),
                ('event_time', models.TimeField()),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_images/')),
                ('sched_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tour_app.tour_schedule')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tour_app.tour_add')),
            ],
        ),
        migrations.DeleteModel(
            name='Admission_fee',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
