# Generated by Django 5.1.6 on 2025-03-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0016_remove_event_tour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour_schedule',
            old_name='tour_id',
            new_name='tour',
        ),
    ]
