# Generated by Django 5.1.6 on 2025-03-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0017_rename_tour_id_tour_schedule_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour_event',
            old_name='tour',
            new_name='tour_id',
        ),
        migrations.RenameField(
            model_name='tour_schedule',
            old_name='tour',
            new_name='tour_id',
        ),
    ]
