# Generated by Django 5.1.6 on 2025-03-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0018_rename_tour_tour_event_tour_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_event',
            name='tour_id',
        ),
        migrations.AlterField(
            model_name='tour_event',
            name='event_ID',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
