# Generated by Django 5.1.6 on 2025-03-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0019_remove_tour_event_tour_id_alter_tour_event_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_Rates',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('payables', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
