# Generated by Django 5.1.6 on 2025-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0020_admission_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_schedule',
            name='slots_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour_schedule',
            name='slots_booked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
