# Generated by Django 5.1.6 on 2025-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0021_tour_schedule_slots_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_add',
            name='tour_id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
