# Generated by Django 5.1.6 on 2025-03-24 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0022_alter_tour_add_tour_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission_rates',
            name='tour_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_rates', to='tour_app.tour_add'),
        ),
    ]
