# Generated by Django 5.1.6 on 2025-03-28 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0024_tour_schedule_cancellation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_admission',
            name='payables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_app.admission_rates'),
        ),
    ]
