# Generated by Django 5.1.7 on 2025-03-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0025_alter_tour_admission_payables'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_schedule',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
