# Generated by Django 5.1.7 on 2025-03-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0026_tour_schedule_duration_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour_event',
            options={'ordering': ['day_number', 'event_time']},
        ),
        migrations.AddField(
            model_name='tour_event',
            name='day_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
