# Generated by Django 5.1.6 on 2025-04-01 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0027_alter_tour_event_options_tour_event_day_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAddTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('tl', 'Tagalog'), ('ceb', 'Cebuano'), ('es', 'Spanish')], max_length=5)),
                ('tour_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tour_app.tour_add')),
            ],
            options={
                'verbose_name': 'Tour Translation',
                'verbose_name_plural': 'Tour Translations',
                'unique_together': {('tour', 'language')},
            },
        ),
    ]
