# Generated by Django 6.0.1 on 2026-02-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0028_touraddtranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour_schedule',
            old_name='tour_id',
            new_name='tour',
        ),
    ]
